version: "3.8"
services:
  cloud-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=cloud_weather_dev
      - POSTGRES_USER=cloud_weather_dev
      - POSTGRES_PASSWORD=cloud_weather_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
volumes:
  postgres_data:
